exclude: (pipelines/report-.*)|(pipelines/.*.txt)|(data_model/src/linkml_crystalia/datamodel/.*.py)
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # General
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: [--unsafe]
      - id: detect-private-key
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: no-commit-to-branch
        stages:
          - pre-push
      - id: trailing-whitespace
      # Json
      - id: check-json
      - id: pretty-format-json # Checks that all your JSON files are pretty.
        args: ['--indent', '2', '--autofix']
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        args: ['--ignore', 'is always evaluated to true']
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
  - repo: https://github.com/ikamensh/flynt/
    rev: '1.0.1'
    hooks:
      - id: flynt
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        args:
          - --py36-plus
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.6.2'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi] # Run on notebooks too.
        exclude: ^(tests)/
      - id: ruff-format
        types_or: [python, pyi] # Run on notebooks too.
  # YAML
  - repo: https://github.com/google/yamlfmt
    rev: v0.10.0
    hooks:
      - id: yamlfmt
  # Secrets
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline', '--exclude-files', 'pnpm-lock.yaml']
  # JSON Schema
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.27.3
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-readthedocs
  # TOML
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
        stages: ["pre-commit"]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
  # Spellcheck
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.13.3
    hooks:
      - id: cspell
