"""Behaviour package for data model v2 (SPARC §7 Interfaces): the single IRI factory and the single
source of coverage, robustness, strength and validity. Runtime deps: stdlib + pydantic.
"""

from __future__ import annotations

from crystalia_data_model.types.bookend import (
    BLOCK,
    STRONG_BY_SIZE,
    DirEntry,
    Verdict,
    judge_bookend,
    mint_bookend,
    mint_bookend_dir,
)
from crystalia_data_model.types.canonical import (
    canonical_bytes,
    hex_of,
    iri_of_hex,
    mint_composite,
    mint_leaf,
    mint_positional,
    nfc,
    recompute_id,
)
from crystalia_data_model.types.coverage import (
    ObjectContext,
    RegionRule,
    asserted,
    comparable,
    coverage_of,
    get_coverage,
    get_robustness,
    literal_coverage,
    mint_md5_chunked,
    register_region_rule,
)
from crystalia_data_model.types.errors import (
    CrystaliaModelError,
    DegenerateCoverage,
    IncompleteRollup,
    InvalidDescriptor,
    RegistryLoadError,
    UnknownType,
    Violation,
    ViolationCode,
)
from crystalia_data_model.types.formats import Detection, Family, FormatEntry, detect_format, lookup, unverified_rules
from crystalia_data_model.types.infer import DEFAULT_RULES, InferenceRule, RuleApply, Stage, cross_algorithm_rule, infer
from crystalia_data_model.types.leaves import (
    mint_count,
    mint_ctime,
    mint_file_size,
    mint_filename,
    mint_format,
    mint_glimpse,
    mint_glimpse_content,
    mint_glimpse_dir_meta,
    mint_glimpse_light,
    mint_glimpse_meta,
    mint_glimpse_slim,
    mint_md5,
    mint_md5_region,
    mint_mtime,
    mint_relpath,
    region_length,
)
from crystalia_data_model.types.provenance import canonical_parameters, mint_method, record_harvest
from crystalia_data_model.types.registry import (
    ChildrenSpec,
    CoverageRule,
    Grade,
    Kind,
    Registry,
    Robustness,
    Role,
    TypeEntry,
    ancestors,
    default_registry,
    grade,
    is_a,
    is_strong,
    type_of,
)
from crystalia_data_model.types.rollup import (
    mint_glimpse_dir,
    mint_glimpse_dir_content,
    mint_glimpse_dir_light,
    mint_glimpse_dir_slim,
    rollup_dir,
)
from crystalia_data_model.types.validate import ensure_valid, validate
from crystalia_data_model.types.zipdesc import ZipMember, mint_zip_cd, mint_zip_manifest, parse_central_directory

__all__ = [
    "BLOCK",
    "DEFAULT_RULES",
    "STRONG_BY_SIZE",
    "ChildrenSpec",
    "CoverageRule",
    "CrystaliaModelError",
    "DegenerateCoverage",
    "Detection",
    "DirEntry",
    "Family",
    "FormatEntry",
    "Grade",
    "IncompleteRollup",
    "InferenceRule",
    "InvalidDescriptor",
    "Kind",
    "ObjectContext",
    "Registry",
    "RegistryLoadError",
    "RegionRule",
    "Robustness",
    "Role",
    "RuleApply",
    "Stage",
    "TypeEntry",
    "UnknownType",
    "Verdict",
    "Violation",
    "ViolationCode",
    "ZipMember",
    "ancestors",
    "asserted",
    "canonical_bytes",
    "canonical_parameters",
    "comparable",
    "coverage_of",
    "cross_algorithm_rule",
    "default_registry",
    "detect_format",
    "ensure_valid",
    "get_coverage",
    "get_robustness",
    "grade",
    "hex_of",
    "infer",
    "iri_of_hex",
    "is_a",
    "is_strong",
    "literal_coverage",
    "lookup",
    "mint_bookend",
    "mint_bookend_dir",
    "mint_composite",
    "mint_count",
    "mint_ctime",
    "mint_file_size",
    "mint_filename",
    "mint_format",
    "mint_glimpse",
    "mint_glimpse_content",
    "mint_glimpse_dir",
    "mint_glimpse_dir_content",
    "mint_glimpse_dir_light",
    "mint_glimpse_dir_meta",
    "mint_glimpse_dir_slim",
    "mint_glimpse_light",
    "mint_glimpse_meta",
    "mint_glimpse_slim",
    "mint_leaf",
    "mint_md5",
    "mint_md5_chunked",
    "mint_md5_region",
    "mint_method",
    "mint_mtime",
    "mint_positional",
    "mint_relpath",
    "mint_zip_cd",
    "mint_zip_manifest",
    "nfc",
    "parse_central_directory",
    "recompute_id",
    "record_harvest",
    "region_length",
    "register_region_rule",
    "rollup_dir",
    "type_of",
    "unverified_rules",
    "validate",
    "judge_bookend",
]
