---
name: python
on:
  push:
  pull_request:
    branches: [main]


jobs:
  types:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
      - name: Install dev group dependencies
        run: pip install '.[dev]'
      - name: Test with Nox
        run: mypy .
  coverage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
      - name: Install dev group dependencies
        run: pip install '.[dev]'
      - name: Install package in place
        run: pip install -e .
      - name: Test with pytest
        run: pytest -n auto --cov --junitxml=junit.xml
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
